# Generated by Django 2.2.4 on 2019-08-11 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 19, 35, 31, 682042), verbose_name='date published'),
        ),
    ]
