# Generated by Django 2.2.4 on 2019-08-11 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190811_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 21, 2, 0, 700763), verbose_name='date published'),
        ),
    ]
