# Generated by Django 2.2.4 on 2019-08-11 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190811_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 22, 1, 20, 515623), verbose_name='date published'),
        ),
    ]
