# Generated by Django 2.2.4 on 2019-08-11 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190811_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 19, 49, 1, 467543), verbose_name='date published'),
        ),
    ]
