# Generated by Django 2.2.4 on 2019-08-13 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190811_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 7, 46, 29, 50275), verbose_name='date published'),
        ),
    ]
