# Generated by Django 2.2.4 on 2019-08-19 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190818_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 18, 44, 55, 485611), verbose_name='date published'),
        ),
    ]
