# Generated by Django 2.2.4 on 2019-08-21 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20190820_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 21, 58, 7, 120751), verbose_name='date published'),
        ),
    ]
