# Generated by Django 2.2.4 on 2019-08-21 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20190820_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 0, 10, 43, 350469), verbose_name='date published'),
        ),
    ]
