# Generated by Django 2.2.4 on 2019-09-02 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20190821_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 23, 46, 47, 350421), verbose_name='date published'),
        ),
    ]
