# Generated by Django 2.2.4 on 2019-09-07 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20190901_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='blog/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 8, 26, 23, 251000), verbose_name='date published'),
        ),
    ]
