# Generated by Django 2.2.4 on 2019-09-09 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20190907_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 7, 35, 28, 562284), verbose_name='date published'),
        ),
    ]
