# Generated by Django 2.2.4 on 2019-11-19 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20190909_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 0, 0, 3, 352779), verbose_name='date published'),
        ),
    ]
