# Generated by Django 2.2.4 on 2019-11-19 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20191119_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 0, 18, 1, 892341), verbose_name='date published'),
        ),
    ]
