# Generated by Django 2.2.4 on 2019-08-11 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190811_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 22, 27, 1, 736046), verbose_name='date published'),
        ),
    ]
