# Generated by Django 2.2.4 on 2019-08-11 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190811_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 23, 2, 39, 423207), verbose_name='date published'),
        ),
    ]
