# Generated by Django 2.2.4 on 2019-08-13 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190811_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 22, 0, 45, 796573), verbose_name='date published'),
        ),
    ]
