# Generated by Django 2.2.4 on 2019-08-13 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190812_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 7, 46, 29, 53492), verbose_name='date published'),
        ),
    ]
