# Generated by Django 2.2.4 on 2019-08-14 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190813_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 9, 3, 4, 910201), verbose_name='date published'),
        ),
    ]
