# Generated by Django 2.2.4 on 2019-08-14 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190814_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 12, 18, 2, 824945), verbose_name='date published'),
        ),
    ]
