# Generated by Django 2.2.4 on 2019-08-18 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190814_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 13, 11, 36, 162476), verbose_name='date published'),
        ),
    ]
