# Generated by Django 2.2.4 on 2019-08-20 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190820_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 4, 2, 13, 341995), verbose_name='date published'),
        ),
    ]
