# Generated by Django 2.2.4 on 2019-08-21 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190820_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 20, 47, 23, 621603), verbose_name='date published'),
        ),
    ]
