# Generated by Django 2.2.4 on 2019-08-21 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190820_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 21, 58, 7, 122723), verbose_name='date published'),
        ),
    ]
