# Generated by Django 2.2.4 on 2019-08-21 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190820_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 0, 10, 43, 353402), verbose_name='date published'),
        ),
    ]
