# Generated by Django 2.2.4 on 2019-09-09 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190907_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 7, 35, 28, 565385), verbose_name='date published'),
        ),
    ]
