# Generated by Django 2.2.4 on 2019-09-09 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190909_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 7, 41, 2, 329331), verbose_name='date published'),
        ),
    ]
